-- ==============================================================================
-- FASE 45: Cola de Correos Persistente
-- ==============================================================================
-- Crea la tabla para gestionar el envío de correos de forma asíncrona y resiliente,
-- permitiendo reintentos y visualización de errores.
--
-- Ejecución: Idempotente. Pegar en el SQL Editor de Supabase.
-- ==============================================================================

-- 1. Crear tabla CORREOS_EN_COLA
CREATE TABLE IF NOT EXISTS public.correos_en_cola (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario VARCHAR(150) NOT NULL,
    asunto VARCHAR(255) NOT NULL,
    cuerpo_html TEXT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_error TEXT,
    fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- 2. Añadir Constraint de Estado (Idempotente)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_correos_estado' 
        AND conrelid = 'public.correos_en_cola'::regclass
    ) THEN
        ALTER TABLE public.correos_en_cola
        ADD CONSTRAINT chk_correos_estado 
        CHECK (estado IN ('PENDIENTE', 'ENVIADO', 'FALLIDO'));
    END IF;
END $$;

-- 3. Índices para búsqueda rápida del Worker
CREATE INDEX IF NOT EXISTS idx_correos_estado_pendientes 
ON public.correos_en_cola(estado) 
WHERE estado IN ('PENDIENTE', 'FALLIDO');

CREATE INDEX IF NOT EXISTS idx_correos_fecha_creacion
ON public.correos_en_cola(fecha_creacion DESC);
